=== John-Salguero/Anbessaw_Salguero_p1/ORM/configuration/salanb-mapping-0.1.dtd
<!-- Salguero and Anbessaw file-based mapping document.

This document defines how the application will map a class.
This has been written with the assistance of
https://xmlwriter.net/xml_guide/doctype_declaration.shtml
And has been heavily inspired by
http://www.hibernate.org/dtd/hibernate-mapping-3.0.dtd
-->

    <!ELEMENT salanb-mapping (class+, meta*)>

    <!ELEMENT meta (#PCDATA)>
    <!ATTLIST meta attribute CDATA #REQUIRED>

    <!ELEMENT class (
            meta*,
            id+,
            property*
            )>
    <!ATTLIST class name CDATA #REQUIRED>                           <!-- this is the class name -->
    <!ATTLIST class table CDATA #IMPLIED>							<!-- default: unqualified classname -->


    <!ELEMENT id (meta*,generator?)>
    <!ATTLIST id name CDATA #REQUIRED>
    <!ATTLIST id column CDATA #REQUIRED>
    <!ATTLIST id type CDATA #REQUIRED>
    <!ATTLIST id length CDATA #IMPLIED>
    <!ATTLIST id precision CDATA #IMPLIED>


    <!-- Property of an entity class or component, component-element, composite-id, etc.
    JavaBeans style properties are mapped to table columns. -->

    <!ELEMENT property (meta*)>
    <!ATTLIST property name CDATA #REQUIRED>
    <!ATTLIST property type CDATA #REQUIRED>
    <!ATTLIST property column CDATA #REQUIRED>
    <!ATTLIST property length CDATA #IMPLIED>
    <!ATTLIST property precision CDATA #IMPLIED>
    <!ATTLIST property not-null (true|false) #IMPLIED>
    <!ATTLIST property unique (true|false) "false">

    <!-- Generators generate unique identifiers. The class attribute specifies a Java
    class implementing an id generation algorithm. -->

    <!ELEMENT generator EMPTY>
    <!ATTLIST generator class CDATA #REQUIRED>

=== John-Salguero/Anbessaw_Salguero_p1/ORM/src/main/resources/Movie.salanb.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE salanb-mapping SYSTEM
        "http://johnsalguero.com/dtd/salanb-mapping-0.1.dtd">
<salanb-mapping>
    <class name = "com.salanb.orm.models.Movie" table = "movies">

        <meta attribute = "class-description">
            This class contains the movie detail.
        </meta>

        <id name = "id" type = "int" column = "m_id">
            <generator class="natural"/>
        </id>

        <property name = "title" column = "title" type = "string"/>
        <property name = "price" column = "price" type = "big_decimal"/>
        <property name = "available" column = "available" type = "boolean"/>
        <property name = "returnDate" column = "return_date" type = "long"/>
        <property name = "director_id" column = "director_id" type = "integer"/>
        <property name = "genre_id" column = "genre_id" type = "integer"/>

    </class>
</salanb-mapping>

=== John-Salguero/Anbessaw_Salguero_p1/ORM/src/test/resources/UserAccounts.salanb.test.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE salanb-mapping SYSTEM
        "http://johnsalguero.com/dtd/salanb-mapping-0.1.dtd">
<salanb-mapping>
    <class name = "testmodels.UserContent">

        <meta attribute = "class-description">
            This class contains the user details.
        </meta>

        <id name = "username" type = "string" column = "Username">
            <generator class="DEFINED"/>
        </id>

        <property name = "firstName" column = "First_Name" type = "string"/>
        <property name = "lastName" column = "Last_Name" type = "string"/>
        <property name = "phoneNumber" column = "Phone_Number" type = "string"/>
        <property name = "emailAddress" column = "Email" type = "string"/>
        <property name = "address" column = "Address_Line_1" type = "string"/>
        <property name = "city" column = "Address_Line_2" type = "string"/>
        <property name = "state" column = "State" type = "string"/>
        <property name = "zipCode" column = "Zip_Code" type = "string"/>
        <property name = "SSN_Hash" column = "SSN_Hash" type = "string"/>
        <property name = "Pass_Hash" column = "Pass_Hash" type = "string"/>

    </class>
    <class name = "testmodels.TestPOJO" table = "testtable">

        <meta attribute = "class-description">
            This class contains the user details.
        </meta>

        <id name = "id" type = "integer" column = "id">
            <generator class="NATURAL"/>
        </id>

        <property name = "int16" column = "int16" type = "short"/>
        <property name = "int32" column = "int32" type = "integer"/>
        <property name = "int64" column = "int64" type = "long"/>
        <property name = "float64" column = "float64" type = "double"/>
        <property name = "string" column = "string" type = "string"/>
        <property name = "character" column = "character" type = "character"/>

    </class>
</salanb-mapping>

=== John-Salguero/Anbessaw_Salguero_p1/WebApp/src/main/resources/ToyStore.salanb.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE salanb-mapping SYSTEM
        "http://johnsalguero.com/dtd/salanb-mapping-0.1.dtd">
<salanb-mapping>
    <class name="com.salanb.webapp.models.Customer" table="Customers">
        <id name="id" column="Customer_Id" type="integer">
            <generator class="NATURAL"/>
        </id>
        <property name="username" type="string" column="Username"/>
        <property name="password" type="string" column="Password"/>
    </class>
    <class name="com.salanb.webapp.models.Product" table="Product">
        <id name="id" type="integer" column="Product_Id">
            <generator class="NATURAL"/>
        </id>
        <property name="name" type="string" column="Name"/>
        <property name="price" type="big_decimal" column="Price"/>
        <property name="isAvailable" type="boolean" column="Available"/>
        <property name="description" type="string" column="Description"/>
    </class>
    <class name="com.salanb.webapp.models.Transaction" table = "Transaction">
        <id name="id" column="Transaction_Id" type="integer">
            <generator class="NATURAL"/>
        </id>
        <property name = "customerId" column="Customer_Id" type ="integer"/>
        <property name="date" type="long" column="Date"/>
        <property name="subtotal" type="big_decimal" column="Subtotal"/>
    </class>
    <class name="com.salanb.webapp.models.Cart" table="Cart">
        <id name="productId" column="Product_Id" type="integer">
            <generator class="DEFINED"/>
        </id>
        <id name = "customerId" column="Customer_Id" type ="integer">
            <generator class = "DEFINED"/>
        </id>
        <property name="amount" column="Amount" type="integer"/>
    </class>
    <class name="com.salanb.webapp.models.TransactionProduct" table="ProductTransaction">
        <id name="productId" column="Product_Id" type="integer">
            <generator class="DEFINED"/>
        </id>
        <id name = "transactionId" column="Transaction_Id" type ="integer">
            <generator class = "DEFINED"/>
        </id>
        <property name="amount" type="integer" column="Amount"/>
    </class>
</salanb-mapping>

=== John-Salguero/Anbessaw_Salguero_p1/WebApp/src/main/resources/Movie.salanb.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE salanb-mapping SYSTEM
        "http://johnsalguero.com/dtd/salanb-mapping-0.1.dtd">
<salanb-mapping>
    <class name = "com.salanb.webapp.models.Movie" table = "movies">

        <meta attribute = "class-description">
            This class contains the movie detail.
        </meta>

        <id name = "id" type = "integer" column = "m_id">
            <generator class="NATURAL"/>
        </id>

        <property name = "title" column = "title" type = "string"/>
        <property name = "price" column = "price" type = "big_decimal"/>
        <property name = "available" column = "available" type = "boolean"/>
        <property name = "returnDate" column = "return_date" type = "long"/>
        <property name = "directorId" column = "director_id" type = "integer"/>
        <property name = "genre_id" column = "genre_id" type = "integer"/>

    </class>
    <class name = "com.salanb.webapp.models.UserContent" table = "User_Data">

        <meta attribute = "class-description">
            This class contains the user details.
        </meta>

        <id name = "username" type = "string" column = "Username">
            <generator class="DEFINED"/>
        </id>

        <property name = "firstName" column = "First_Name" type = "string"/>
        <property name = "lastName" column = "Last_Name" type = "string"/>
        <property name = "phoneNumber" column = "Phone_Number" type = "string"/>
        <property name = "emailAddress" column = "Email" type = "string"/>
        <property name = "address" column = "Address_Line_1" type = "string"/>
        <property name = "city" column = "Address_Line_2" type = "string"/>
        <property name = "state" column = "State" type = "string"/>
        <property name = "zipCode" column = "Zip_Code" type = "string"/>
        <property name = "SSN_Hash" column = "SSN_Hash" type = "string"/>
        <property name = "Pass_Hash" column = "Pass_Hash" type = "string"/>

    </class>
</salanb-mapping>

=== John-Salguero/Anbessaw_Salguero_p1/ORM/src/test/resources/PKTest.test.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE salanb-mapping SYSTEM
        "http://johnsalguero.com/dtd/salanb-mapping-0.1.dtd">
<salanb-mapping>
    <class name = "testmodels.UserContent">

        <meta attribute = "class-description">
            This class contains the user details.
        </meta>

        <id name = "username" type = "string" column = "Username">
            <generator class="DEFINED"/>
        </id>

        <property name = "firstName" column = "First_Name" type = "string"/>
        <property name = "lastName" column = "Last_Name" type = "string"/>
        <property name = "phoneNumber" column = "Phone_Number" type = "string"/>
        <property name = "emailAddress" column = "Email" type = "string"/>
        <property name = "address" column = "Address_Line_1" type = "string"/>
        <property name = "city" column = "Address_Line_2" type = "string"/>
        <property name = "state" column = "State" type = "string"/>
        <property name = "zipCode" column = "Zip_Code" type = "string"/>
        <property name = "SSN_Hash" column = "SSN_Hash" type = "string"/>
        <property name = "Pass_Hash" column = "Pass_Hash" type = "string"/>

    </class>
    <class name = "testmodels.TestPOJO" table = "testtable">

        <meta attribute = "class-description">
            This class contains the user details.
        </meta>

        <id name = "id" type = "integer" column = "id">
            <generator class="FRAMEWORK"/>
        </id>

        <id name = "int16" column = "int16" type = "short">
            <generator class="FRAMEWORK"/>
        </id>
        <id name = "int32" column = "int32" type = "integer">
        </id>
        <id name = "int64" column = "int64" type = "long">
            <generator class="FRAMEWORK"/>
        </id>
        <id name = "float64" column = "float64" type = "double">
            <generator class="FRAMEWORK"/>
        </id>
        <id name = "string" column = "string" type = "string">
            <generator class="FRAMEWORK"/>
        </id>
        <id name = "character" column = "character" type = "character">
            <generator class="DEFINED"/>
        </id>
    </class>
</salanb-mapping>
