=== John-Salguero/Anbessaw_Salguero_p1/ORM/configuration/salanb-configuration-0.1.dtd
<!-- Salguero and Anbessaw file-based configuration document.

This document defines how the application will be using the ORM.
This has been written with the assistance of 
https://xmlwriter.net/xml_guide/doctype_declaration.shtml
And has been heavily inspired by
http://www.hibernate.org/dtd/hibernate-configuration-3.0.dtd
-->

<!DOCTYPE salanb-configuration [

<!ELEMENT salanb-configuration (session-factory+)>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>

<!ELEMENT mapping EMPTY> <!-- reference to a mapping file -->
<!ATTLIST mapping resource CDATA #IMPLIED>

<!ELEMENT session-factory (property*, mapping*)>
<!ATTLIST session-factory name CDATA #IMPLIED> 

]>

=== John-Salguero/Anbessaw_Salguero_p1/ORM/src/test/resources/SalAnb.cfg.sad.format.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE salanb-configuration SYSTEM
        "http://johnsalguero.com/dtd/salanb-configuration-0.1.dtd">
<salanb-configuration>
    <session-factory>

        <property name = "driver_class">
            org.postgresql.Driver
        </property>

        <property name = "url">
            jdbc:mysql://localhost/test
        </property>

        <property name = "username">
            root
        </property>

        <property name = "password">
            root123
        </property>

        <!-- List of XML mapping files -->
        <mapping resource = "Movie.salanb.test.xml"/>
        <mapping resource = "UserAccounts.salanb.test.xml"/>

    </session-factory>
</salanb-configuration>

=== John-Salguero/Anbessaw_Salguero_p1/ORM/src/test/resources/SalAnb.cfg.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE salanb-configuration SYSTEM
        "http://johnsalguero.com/dtd/salanb-configuration-0.1.dtd">
<salanb-configuration>
    <session-factory>

        <property name = "salanb.connection.driver_class">
            org.postgresql.Driver
        </property>

        <property name = "salanb.connection.url">
            jdbc:postgresql://john2201javareact.c52ukl0dxifi.us-east-1.rds.amazonaws.com:5432/postgres
        </property>

        <property name = "salanb.connection.username">
            postgres
        </property>

        <property name = "salanb.connection.password">
            vnvBv3exzYY7pavbGo6b
        </property>

        <!-- List of XML mapping files -->
        <mapping resource = "Movie.salanb.test.xml"/>
        <mapping resource = "UserAccounts.salanb.test.xml"/>
        <mapping resource = "ToyStore.salanb.xml"/>
    </session-factory>
    <session-factory name="PK">

        <property name = "salanb.connection.driver_class">
            org.postgresql.Driver
        </property>

        <property name = "salanb.connection.url">
            jdbc:postgresql://john2201javareact.c52ukl0dxifi.us-east-1.rds.amazonaws.com:5432/postgres
        </property>

        <property name = "salanb.connection.username">
            postgres
        </property>

        <property name = "salanb.connection.password">
            vnvBv3exzYY7pavbGo6b
        </property>

        <!-- List of XML mapping files -->
        <mapping resource = "Movie.salanb.test.xml"/>
        <mapping resource = "PKTest.test.xml"/>
    </session-factory>
    <session-factory name="Defined">

        <property name = "salanb.connection.driver_class">
            org.postgresql.Driver
        </property>

        <property name = "salanb.connection.url">
            jdbc:postgresql://john2201javareact.c52ukl0dxifi.us-east-1.rds.amazonaws.com:5432/postgres
        </property>

        <property name = "salanb.connection.username">
            postgres
        </property>

        <property name = "salanb.connection.password">
            vnvBv3exzYY7pavbGo6b
        </property>

        <!-- List of XML mapping files -->
        <mapping resource = "Movie.salanb.test.xml"/>
        <mapping resource = "Defined.test.xml"/>
    </session-factory>
</salanb-configuration>
